# Generated by Django 3.1.4 on 2021-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210107_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Отправка уведомлений'),
        ),
    ]
