# Generated by Django 3.1.4 on 2021-01-08 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslog',
            name='seller',
        ),
        migrations.AddField(
            model_name='saleslogdetail',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customers', related_query_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='saleslogdetail',
            name='seller',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', related_query_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
