# Generated by Django 3.1.4 on 2020-12-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='category', to='records.category', verbose_name='Категория товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', related_query_name='group_product', to='records.groupproduct', verbose_name='Группы товаров'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', related_query_name='parameter', to='records.parameter', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_products', related_query_name='parameter_product', to='records.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', related_query_name='seller', to='records.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='saleslogdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_products', related_query_name='detail_product', to='records.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='saleslogdetail',
            name='sales_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_logs', related_query_name='sales_log', to='records.saleslog', verbose_name='Журнал'),
        ),
    ]
