# Generated by Django 3.1.4 on 2021-01-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210108_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
