# Generated by Django 3.1.4 on 2020-12-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20201229_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', related_query_name='category_category', to='records.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_parameters', related_query_name='parameter_parameter', to='records.parameter', verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', related_query_name='product_category', to='records.category', verbose_name='Категория товаров'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameter_parameters', related_query_name='product_parameter_parameter', to='records.parameter', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameter_products', related_query_name='product_parameter_product', to='records.product', verbose_name='Товары'),
        ),
    ]
