# Generated by Django 3.1.4 on 2020-12-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20201229_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', related_query_name='category_category', to='records.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_parameters', related_query_name='parameter_parameter', to='records.parameter', verbose_name='Набор'),
        ),
    ]
