# Generated by Django 3.1.4 on 2021-01-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_delete_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleslog',
            options={'verbose_name': 'Данные журнала продаж', 'verbose_name_plural': 'Данные журнала продаж'},
        ),
        migrations.AlterModelOptions(
            name='saleslogdetail',
            options={'verbose_name': 'Детали по журналу продаж', 'verbose_name_plural': 'Детали по журналу продаж'},
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='saleslogdetail',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Комментарий'),
        ),
    ]
