# Generated by Django 3.1.4 on 2020-12-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20201229_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_categories', related_query_name='parameter_category', to='records.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Группа активна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Товар активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Товар в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterIndexTogether(
            name='productparameter',
            index_together={('product', 'parameter')},
        ),
    ]
