# Generated by Django 3.1.4 on 2021-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20210108_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslogdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
