# Generated by Django 3.1.4 on 2021-01-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20210108_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Комбинация параметров товара', 'verbose_name_plural': 'Комбинации параметров  товаров'},
        ),
        migrations.AlterModelOptions(
            name='saleslog',
            options={'verbose_name': 'Продажи', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='vendor_code',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность товара'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование товара'),
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=15, verbose_name='Артикул')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Товар активен')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная стоимость товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('group_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_products', related_query_name='group_product', to='records.groupproduct', verbose_name='Группы товаров')),
            ],
            options={
                'verbose_name': 'Информация по товару',
                'verbose_name_plural': 'Информация по товарам',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', related_query_name='products_info', to='records.productinfo', verbose_name='Информация по товару'),
        ),
    ]
