# Generated by Django 3.1.4 on 2021-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Закупочная стоимость товара'),
        ),
        migrations.AlterField(
            model_name='saleslogdetail',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена товара'),
        ),
    ]
