# Generated by Django 3.1.4 on 2021-01-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20210110_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AddField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='image',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info_image', to='records.productinfo', verbose_name='Товары'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
