# Generated by Django 3.1.4 on 2021-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20210116_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='display_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отображение параметра'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='display_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг'),
        ),
    ]
