# Generated by Django 3.1.4 on 2021-01-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20210116_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.productinfo', verbose_name='Товары'),
        ),
    ]
