# Generated by Django 3.1.4 on 2021-01-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20210116_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='records.productinfo', verbose_name='Товары'),
        ),
    ]
