# Generated by Django 3.1.4 on 2021-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20210116_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='sort_number',
            field=models.IntegerField(default=1, verbose_name='Номер по-порядку'),
            preserve_default=False,
        ),
    ]
